### ISSUE TITLE
App crashes when using ”Site” or “Visit” options using iOS 14

### ISSUE THREAD

**Issue by gginsberg** [rbevans-ugh/runCLTrun-Bugs#1]
I’m running latest public beta of iOS14. If I go to Shop->(any store) and click on the “Site” button (Safari icon) the app immediately crashes.

Likewise, clicking Run->(any of the three choices) and click on the red “Visit” button for any of the run clubs create an immediate crash.

Same thing for any the items under  “Do good”

**Comment by arbyruns** [comment]
Thanks for the report!  Are you running test flight or from the app store?  In the next release I'm using Xcode 14 now so I'm wondering if that will resolve the issue.

**Comment by gginsberg** [comment]
Yes. Currently testing a number of apps for my employer (a d a few public apps) viaTestflight.   
  
  
  
>

**Comment by arbyruns** [comment]
I think it's an issue with iOS14.  I don't have the issue with iOS13 or not Xcode 13.  I've reported this to Apple.  Thanks again for reporting!

**Comment by arbyruns** [comment]
I think I fixed this issue and will be sending out an update on testflight.

**Comment by gginsberg** [comment]
Gotcha...and no, I don't have the TestFlight version of your app (I think that's what you were originally asking...not if I had Testflight itself). I'll be happy to test if you'd like.

**Comment by arbyruns** [comment]
That would be great, here's the [link](https://testflight.apple.com/join/Bit1EPMZ)!
