### ISSUE TITLE
Rub Club

### ISSUE THREAD

**Issue by reitz37** [rbevans-ugh/runCLTrun-Bugs#2]
The pop up about runCLTrun version 1.1 says Rub Club. 
This occurs when I first went into the app.

**Comment by arbyruns** [comment]
Thanks! Someone else also reported this today. Sorry about that!

**Comment by arbyruns** [comment]
Resolved

**Comment by reitz37** [comment]
FYI…I don’t think I’m that I’ve submitted any bugs in well over a year. This may have been sent in error. Or it was deep in the backlog of fixes. 

Thanks for all you’re doing with the app. 
- Tim

**Comment by arbyruns** [comment]
Thanks Tim!  I was cleaning up old bugs.  Sorry about that and glad you're enjoying the app!
