### ISSUE TITLE
Run Club sort order & Collapse / Expand days

### ISSUE THREAD

**Issue by gginsberg** [rbevans-ugh/runCLTrun-Bugs#3]
In its current form Run Club starts with Monday. That puts Sat & Sun at the bottom of what could be a very long list of entries. Given that IMHO most people would be looking for weekend runs, I might suggest starting the list w/ Saturday. Then again, if you could collapse the days and just let the user expand the list, that would be work too.

**Comment by arbyruns** [comment]
That's really good feedback.  I'll go ahead and rearrange the days of the week for a quick fix in the next build and look into collapsing list sections for a long term solution.

**Comment by arbyruns** [comment]
@gginsberg this turned out to a bit easier than I thought.  I should have the collapsing in the next beta build.
